import type { Metadata } from "next";
import {
  Revalia,
  Jersey_15,
  Pixelify_Sans,
  Roboto_Slab,
} from "next/font/google";
import "./globals.css";

const revalia = Revalia({
  variable: "--font-revalia",
  weight: "400",
});

const jersey = Jersey_15({
    variable: "--font-jersey",
    weight: "400",
});

const pixelify = Pixelify_Sans({
  variable: "--font-pixelify",
  weight: ["400", "500", "600", "700"],
});

const robotoSlab = Roboto_Slab({
  variable: "--font-robotoslab",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${revalia.variable} ${jersey.variable} ${pixelify.variable} ${robotoSlab.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
